from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

def rep(old,new,count=1):
    global s
    assert old in s, f'missing pattern: {old[:120]}'
    s=s.replace(old,new,count)

def sub(pattern,repl,count=1):
    global s
    ns,n=re.subn(pattern,repl,s,count=count,flags=re.S)
    assert n==count, f'pattern count {n} != {count}: {pattern[:120]}'
    s=ns

# Version/schema + local telemetry key.
rep('const APP_VERSION="4.1.0";\nconst DATA_VERSION=5;', 'const APP_VERSION="4.2.0";\nconst DATA_VERSION=6;')
rep('const COLLAPSE_KEY="doctrin-todo-collapsed-v1";', 'const COLLAPSE_KEY="doctrin-todo-collapsed-v1";\nconst FRICTION_KEY="doctrin-todo-friction-v1";')
rep('const VERSION_HISTORY=[\n {version:"4.1.0"', 'const VERSION_HISTORY=[\n {version:"4.2.0",date:"2026-08-16",text:"Development jobs from backlog plus local friction monitoring for repeated/no-op actions, undo/toggle loops, edit churn, navigation bounce, failed searches and sync trouble."},\n {version:"4.1.0"')

# Nav + visual language.
rep('    <button data-view="history"><span>Backlog & historik</span><span class="count" id="cBacklog">0</span></button>', '    <button data-view="history"><span>Backlog & historik</span><span class="count" id="cBacklog">0</span></button>\n    <button data-view="friction"><span>Friktion</span><span class="count" id="cFriction">0</span></button>')
rep('.selftest{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;padding:24px;background:#111;color:#ddd;min-height:100vh}', '.devjob{border-top:1px solid #ece9e2;padding:10px 0}.devjob:first-child{border-top:0}.devjob-actions,.friction-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.devjob-actions button,.friction-actions button{border:1px solid var(--line);background:#faf9f6;border-radius:7px;padding:5px 8px;font-size:11px}.friction-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin:12px 0 18px}.friction-stat{background:#faf9f6;border:1px solid var(--line);border-radius:10px;padding:10px}.friction-stat strong{display:block;font-size:20px}.friction-signal{border-top:1px solid #ece9e2;padding:12px 0}.friction-signal:first-of-type{border-top:0}.friction-score{display:inline-block;font-size:10px;font-weight:750;padding:2px 6px;border-radius:99px;background:var(--danger-soft);color:var(--danger);margin-left:6px}.monitor-row{display:flex;gap:10px;align-items:center;justify-content:space-between;background:#faf9f6;border:1px solid var(--line);border-radius:10px;padding:10px 12px;margin-bottom:12px}.monitor-row label{display:flex;gap:7px;align-items:center;font-size:12px;font-weight:700}.privacy-note{font-size:11px;color:var(--muted);line-height:1.45}.selftest{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;padding:24px;background:#111;color:#ddd;min-height:100vh}')
rep('@media(max-width:900px){.addrow', '@media(max-width:900px){.friction-grid{grid-template-columns:repeat(2,1fr)}.addrow')

# State/data models.
rep('const state={tasks:[],backlog:[],updatedAt:new Date().toISOString(),view:"upcoming",query:"",undoStack:[],selectedId:null,inlineEditId:null,inlineFocus:"title",editingId:null,newFlags:{next:false,followup:false,some:false},collapsed:new Set()};', 'const state={tasks:[],backlog:[],devJobs:[],updatedAt:new Date().toISOString(),view:"upcoming",query:"",undoStack:[],selectedId:null,inlineEditId:null,inlineFocus:"title",editingId:null,newFlags:{next:false,followup:false,some:false},collapsed:new Set()};\nlet friction={enabled:true,events:[],signals:[],dismissed:0,lastSignalAt:{}};')
rep('function seedBacklog(){return DEFAULT_BACKLOG.map(normalizeBacklogItem)}', '''function seedBacklog(){return DEFAULT_BACKLOG.map(normalizeBacklogItem)}
function normalizeDevJob(x){return{id:x.id||uid(),createdAt:x.createdAt||new Date().toISOString(),updatedAt:x.updatedAt||x.createdAt||new Date().toISOString(),status:["ready","handed-off","done","failed"].includes(x.status)?x.status:"ready",backlogIds:Array.isArray(x.backlogIds)?x.backlogIds.map(String):[],prompt:String(x.prompt||""),note:String(x.note||"")}}
function defaultFriction(){return{enabled:true,events:[],signals:[],dismissed:0,lastSignalAt:{}}}
function normalizeFriction(x){const f=defaultFriction();if(!x||typeof x!=="object")return f;f.enabled=x.enabled!==false;f.events=Array.isArray(x.events)?x.events.slice(-250):[];f.signals=Array.isArray(x.signals)?x.signals.slice(0,80):[];f.dismissed=Number(x.dismissed)||0;f.lastSignalAt=x.lastSignalAt&&typeof x.lastSignalAt==="object"?x.lastSignalAt:{};return f}
function loadFriction(){try{friction=normalizeFriction(JSON.parse(localStorage.getItem(FRICTION_KEY)||"null"))}catch{friction=defaultFriction()}}
function saveFriction(){localStorage.setItem(FRICTION_KEY,JSON.stringify(friction))}
function cleanTarget(v){return String(v||"").replace(/[^a-zA-Z0-9_:\-.]/g,"_").slice(0,120)}
function tinyHash(v){let h=2166136261;for(const c of String(v||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function interactionFingerprint(){return hashData()+"|"+state.view+"|"+state.query+"|"+(state.inlineEditId||"")+"|"+[...state.collapsed].sort().join(",")}
function recentEvents(type,ms,target=null){const since=Date.now()-ms;return friction.events.filter(e=>e.ts>=since&&(!type||e.type===type)&&(target===null||e.target===target))}
function emitFrictionSignal(kind,target,title,description,score){const key=kind+"|"+target,now=Date.now(),last=Number(friction.lastSignalAt[key]||0);if(now-last<10*60*1000)return null;friction.lastSignalAt[key]=now;const sig={id:uid(),kind,target,title,description,score,detectedAt:new Date(now).toISOString(),status:"open"};friction.signals.unshift(sig);friction.signals=friction.signals.slice(0,80);saveFriction();if(!TEST_MODE)notice("Friktion upptäckt · "+title);return sig}
function detectFriction(){if(!friction.enabled)return;const last=friction.events[friction.events.length-1];if(!last)return;const noops=recentEvents("click",20000,last.target).filter(e=>e.meta?.changed===false);if(last.type==="click"&&last.meta?.changed===false&&noops.length>=3)emitFrictionSignal("repeated-noop",last.target,"Upprepade klick utan resultat",`${noops.length} klick på samma kontroll inom 20 sekunder utan observerbar state-förändring.`,4);const undos=recentEvents("undo",120000);if(undos.length>=3)emitFrictionSignal("undo-burst","global","Många Undo i följd",`${undos.length} Undo inom två minuter.`,5);if(last.type==="toggle"){const toggles=recentEvents("toggle",180000,last.target);if(toggles.length>=4)emitFrictionSignal("toggle-loop",last.target,"Tagg eller status växlas fram och tillbaka",`${toggles.length} växlingar på samma objekt inom tre minuter.`,4)}if(last.type==="edit"){const edits=recentEvents("edit",300000,last.target);if(edits.length>=4)emitFrictionSignal("edit-churn",last.target,"Samma todo redigeras upprepade gånger",`${edits.length} redigeringar av samma todo inom fem minuter.`,3)}if(last.type==="nav"){const nav=recentEvents("nav",120000),u=new Set(nav.map(e=>e.target));if(nav.length>=6&&u.size<=3)emitFrictionSignal("nav-bounce","views","Du hoppar fram och tillbaka mellan vyer",`${nav.length} vybyten mellan ${u.size} vyer inom två minuter.`,3)}if(last.type==="search"&&last.meta?.results===0){const miss=recentEvents("search",90000,last.target).filter(e=>e.meta?.results===0);if(miss.length>=3)emitFrictionSignal("search-miss",last.target,"Samma sökning ger ingen träff",`${miss.length} sökförsök utan resultat inom 90 sekunder.`,3)}if(last.type==="sync_error"){const errs=recentEvents("sync_error",600000);if(errs.length>=2)emitFrictionSignal("sync-trouble","dropbox","Återkommande synkproblem",`${errs.length} synkfel inom tio minuter.`,5)}if(last.type==="rollback"){const rolls=recentEvents("rollback",600000);if(rolls.length>=2)emitFrictionSignal("rollback-loop","global","Flera rollback på kort tid",`${rolls.length} rollback inom tio minuter.`,5)}}
function recordFrictionEvent(type,target="",meta={}){if(TEST_MODE||!friction.enabled)return;friction.events.push({id:uid(),ts:Date.now(),type,target:cleanTarget(target),meta:{...meta}});friction.events=friction.events.slice(-250);detectFriction();saveFriction()}
function recordFrictionEventForTest(type,target="",meta={}){friction.events.push({id:uid(),ts:Date.now(),type,target:cleanTarget(target),meta:{...meta}});friction.events=friction.events.slice(-250);detectFriction();saveFriction()}
''')

# Persist dev jobs with user data; friction remains local telemetry.
rep('function hashData(tasks=state.tasks,backlog=state.backlog){return JSON.stringify({tasks:tasks.map(t=>[t.id,t.title,t.notes,t.dueDate,t.completed,t.completedAt,t.cleared,t.path,t.tags]),backlog:backlog.map(b=>[b.id,b.type,b.title,b.description,b.selected,b.comment,b.status])})}', 'function hashData(tasks=state.tasks,backlog=state.backlog,devJobs=state.devJobs){return JSON.stringify({tasks:tasks.map(t=>[t.id,t.title,t.notes,t.dueDate,t.completed,t.completedAt,t.cleared,t.path,t.tags]),backlog:backlog.map(b=>[b.id,b.type,b.title,b.description,b.selected,b.comment,b.status]),devJobs:devJobs.map(j=>[j.id,j.status,j.backlogIds,j.prompt,j.note])})}')
sub(r'function load\(\)\{.*?\}\nfunction saveLocal\(touch=true\)\{.*?\}', '''function load(){try{const obj=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(obj&&Array.isArray(obj.tasks)){state.tasks=obj.tasks.map(normalizeTask);state.backlog=Array.isArray(obj.backlog)?obj.backlog.map(normalizeBacklogItem):seedBacklog();state.devJobs=Array.isArray(obj.devJobs)?obj.devJobs.map(normalizeDevJob):[];state.updatedAt=obj.updatedAt||new Date().toISOString()}else{state.tasks=[];state.backlog=seedBacklog();state.devJobs=[]}}catch{state.tasks=[];state.backlog=seedBacklog();state.devJobs=[]}loadCollapsed();loadFriction();saveLocal(false)}
function saveLocal(touch=true){if(touch)state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify({version:DATA_VERSION,appVersion:APP_VERSION,updatedAt:state.updatedAt,tasks:state.tasks,backlog:state.backlog,devJobs:state.devJobs}))}''')
rep('function createSnapshot(reason){if(!state.tasks.length&&!state.backlog.length)return;const a=snapshots(),fingerprint=hashData();if(a[0]?.fingerprint===fingerprint)return;a.unshift({id:uid(),createdAt:new Date().toISOString(),reason,version:APP_VERSION,fingerprint,tasks:JSON.parse(JSON.stringify(state.tasks)),backlog:JSON.parse(JSON.stringify(state.backlog))});setSnapshots(a)}', 'function createSnapshot(reason){if(!state.tasks.length&&!state.backlog.length&&!state.devJobs.length)return;const a=snapshots(),fingerprint=hashData();if(a[0]?.fingerprint===fingerprint)return;a.unshift({id:uid(),createdAt:new Date().toISOString(),reason,version:APP_VERSION,fingerprint,tasks:JSON.parse(JSON.stringify(state.tasks)),backlog:JSON.parse(JSON.stringify(state.backlog)),devJobs:JSON.parse(JSON.stringify(state.devJobs))});setSnapshots(a)}')
rep('function pushUndo(label){state.undoStack.push({label,tasks:JSON.parse(JSON.stringify(state.tasks)),backlog:JSON.parse(JSON.stringify(state.backlog))});if(state.undoStack.length>50)state.undoStack.shift();createSnapshot("Before: "+label)}', 'function pushUndo(label){state.undoStack.push({label,tasks:JSON.parse(JSON.stringify(state.tasks)),backlog:JSON.parse(JSON.stringify(state.backlog)),devJobs:JSON.parse(JSON.stringify(state.devJobs))});if(state.undoStack.length>50)state.undoStack.shift();createSnapshot("Before: "+label)}')
rep('function undo(){const prev=state.undoStack.pop();if(!prev){notice("Inget att ångra");return}createSnapshot("Before undo");state.tasks=(prev.tasks||[]).map(normalizeTask);state.backlog=(prev.backlog||state.backlog).map(normalizeBacklogItem);save();render();notice("Ångrade: "+prev.label)}', 'function undo(){const prev=state.undoStack.pop();if(!prev){notice("Inget att ångra");return}recordFrictionEvent("undo","global",{label:prev.label});createSnapshot("Before undo");state.tasks=(prev.tasks||[]).map(normalizeTask);state.backlog=(prev.backlog||state.backlog).map(normalizeBacklogItem);state.devJobs=(prev.devJobs||state.devJobs).map(normalizeDevJob);save();render();notice("Ångrade: "+prev.label)}')
rep('function restoreSnapshot(id){const snap=snapshots().find(s=>s.id===id);if(!snap)return;createSnapshot("Before rollback");state.tasks=(snap.tasks||[]).map(normalizeTask);if(Array.isArray(snap.backlog))state.backlog=snap.backlog.map(normalizeBacklogItem);save();render();notice("Rollback genomförd")}', 'function restoreSnapshot(id){const snap=snapshots().find(s=>s.id===id);if(!snap)return;recordFrictionEvent("rollback","snapshot",{});createSnapshot("Before rollback");state.tasks=(snap.tasks||[]).map(normalizeTask);if(Array.isArray(snap.backlog))state.backlog=snap.backlog.map(normalizeBacklogItem);if(Array.isArray(snap.devJobs))state.devJobs=snap.devJobs.map(normalizeDevJob);save();render();notice("Rollback genomförd")}')

# Development jobs.
rep('function generatePromptText(){', '''function developmentPrompt(items){let s="Implementera följande ändringar i repository stravus/todo. Arbeta på feature branch och skapa en reviewbar PR; skriv aldrig privata todo-data i repositoryt.\\n\\n";items.forEach((b,i)=>{s+=`${i+1}. [${b.type==="bug"?"BUG":"FÖRBÄTTRING"}] ${b.title}\\n`;if(b.description)s+=`   Beskrivning: ${b.description}\\n`;if(b.comment)s+=`   Kommentar: ${b.comment}\\n`;s+="\\n"});s+="Krav: behåll data-/Dropbox-kompatibilitet, uppdatera versionshistorik och testlogg, kör syntax-, funktions-, migration- och riktig browser-regression. Merge/publicera inte om tester fallerar.";return s}
function createDevJob(){const items=state.backlog.filter(b=>b.selected&&b.status!=="done");if(!items.length){notice("Markera minst en backlog-post");return null}pushUndo("create development job");const job=normalizeDevJob({backlogIds:items.map(b=>b.id),prompt:developmentPrompt(items),status:"ready"});state.devJobs.unshift(job);save();render();notice("Development job skapat");return job}
async function copyDevJob(id){const j=state.devJobs.find(x=>x.id===id);if(!j)return;try{await navigator.clipboard.writeText(j.prompt);notice("Development prompt kopierad")}catch{notice("Kunde inte kopiera prompt")}}
function handoffDevJob(id){const j=state.devJobs.find(x=>x.id===id);if(!j)return;const title=`Todo development job ${APP_VERSION} · ${j.backlogIds.length} poster`,body=j.prompt+`\\n\\nDevelopment job ID: ${j.id}`;j.status="handed-off";j.updatedAt=new Date().toISOString();save();window.open(`https://github.com/stravus/todo/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`,"_blank","noopener");render()}
function setDevJobStatus(id,status){const j=state.devJobs.find(x=>x.id===id);if(!j)return;j.status=["ready","handed-off","done","failed"].includes(status)?status:j.status;j.updatedAt=new Date().toISOString();save();render()}
function devJobsHtml(){if(!state.devJobs.length)return`<div class="item-copy">Inga development jobs ännu.</div>`;return state.devJobs.slice(0,10).map(j=>`<div class="devjob" data-devjob="${esc(j.id)}"><div class="item-title">${esc(new Intl.DateTimeFormat("sv-SE",{dateStyle:"short",timeStyle:"short"}).format(new Date(j.createdAt)))} <span class="pill ${j.status==="done"?"done":""}">${esc(j.status)}</span></div><div class="item-copy">${j.backlogIds.length} backlog-poster · job ${esc(j.id.slice(0,8))}</div><div class="devjob-actions"><button data-jcopy="${esc(j.id)}">Kopiera prompt</button><button data-jhandoff="${esc(j.id)}">Öppna GitHub-uppdrag</button><select data-jstatus="${esc(j.id)}"><option value="ready" ${j.status==="ready"?"selected":""}>ready</option><option value="handed-off" ${j.status==="handed-off"?"selected":""}>handed-off</option><option value="done" ${j.status==="done"?"selected":""}>done</option><option value="failed" ${j.status==="failed"?"selected":""}>failed</option></select></div></div>`).join("")}
function generatePromptText(){''')
# Keep manual prompt behavior but make it use the same hardened prompt.
sub(r'function generatePromptText\(\)\{const a=state\.backlog\.filter\(b=>b\.selected&&b\.status!=="done"\);if\(!a\.length\)return"";let s=.*?return s\}', 'function generatePromptText(){const a=state.backlog.filter(b=>b.selected&&b.status!=="done");return a.length?developmentPrompt(a):""}', 1)

# Backlog UI: add job creation + recent jobs.
sub(r'function backlogHtml\(\)\{(.*?)<div class="prompt-toolbar"><button class="btn primary" id="generatePromptBtn">Generera prompt</button><button class="btn" id="copyPromptBtn">Kopiera prompt</button></div><textarea class="prompt-box" id="promptBox" placeholder="Markerade backlog-poster hamnar här…"></textarea></section>`\}', r'''function backlogHtml(){\1<div class="prompt-toolbar"><button class="btn primary" id="createDevJobBtn">Implementera markerade</button><button class="btn" id="generatePromptBtn">Generera prompt</button><button class="btn" id="copyPromptBtn">Kopiera prompt</button></div><div class="item-copy">Implementera markerade skapar ett synkat development job. GitHub-handoff öppnar ett förifyllt uppdrag utan att lagra GitHub/OpenAI-hemligheter i appen.</div><textarea class="prompt-box" id="promptBox" placeholder="Markerade backlog-poster hamnar här…"></textarea><h3>Development jobs</h3>${devJobsHtml()}</section>`}''')

# Friction dashboard + bug conversion.
rep('function historyHtml(){', '''function frictionOpen(){return friction.signals.filter(x=>x.status==="open")}
function frictionStats(){const since=Date.now()-7*86400000,ev=friction.events.filter(e=>e.ts>=since);return{events:ev.length,undo:ev.filter(e=>e.type==="undo").length,noops:ev.filter(e=>e.type==="click"&&e.meta?.changed===false).length,signals:frictionOpen().length}}
function frictionHtml(){const st=frictionStats(),signals=friction.signals.filter(x=>x.status!=="dismissed");return`<div data-friction-ui><section class="panel"><div class="monitor-row"><label><input type="checkbox" id="frictionEnabled" ${friction.enabled?"checked":""}> Friction monitor aktiv</label><button class="btn" id="clearFrictionEvents">Rensa eventlogg</button></div><div class="privacy-note">Eventloggen lagras endast lokalt på den här enheten och innehåller action, tekniskt mål-ID, tid och enkel before/after-information — inte todo-texter. Buggar du skapar här blir vanlig backlog och synkas till Dropbox.</div><div class="friction-grid"><div class="friction-stat"><strong>${st.signals}</strong><span>öppna signaler</span></div><div class="friction-stat"><strong>${st.undo}</strong><span>Undo · 7 dagar</span></div><div class="friction-stat"><strong>${st.noops}</strong><span>no-op klick · 7 dagar</span></div><div class="friction-stat"><strong>${st.events}</strong><span>events · 7 dagar</span></div></div><h2>Upptäckta mönster</h2>${signals.length?signals.map(x=>`<div class="friction-signal" data-signal="${esc(x.id)}"><div class="item-title">${esc(x.title)}<span class="friction-score">score ${x.score}</span>${x.status==="backlog"?`<span class="pill done">bug skapad</span>`:""}</div><div class="item-copy">${esc(x.description)} · ${esc(new Intl.DateTimeFormat("sv-SE",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.detectedAt)))}</div>${x.status==="open"?`<div class="friction-actions"><button data-signalbug="${esc(x.id)}">Skapa bug</button><button data-signaldismiss="${esc(x.id)}">Ignorera</button></div>`:""}</div>`).join(""):`<div class="empty">Inga friktionssignaler ännu.</div>`}</section></div>`}
function signalToBug(id){const x=friction.signals.find(s=>s.id===id);if(!x||x.status!=="open")return;state.backlog.unshift(normalizeBacklogItem({type:"bug",title:`Friktion: ${x.title}`,description:`Automatiskt upptäckt ${new Intl.DateTimeFormat("sv-SE",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.detectedAt))}. ${x.description} Teknisk signal: ${x.kind}; mål: ${x.target}.`}));x.status="backlog";saveFriction();save();render();notice("Bug skapad i backlog")}
function dismissSignal(id){const x=friction.signals.find(s=>s.id===id);if(!x)return;x.status="dismissed";friction.dismissed++;saveFriction();render()}
function bindFriction(){document.getElementById("frictionEnabled")?.addEventListener("change",e=>{friction.enabled=e.target.checked;saveFriction();render()});document.getElementById("clearFrictionEvents")?.addEventListener("click",()=>{friction.events=[];saveFriction();render()});document.querySelectorAll("[data-signalbug]").forEach(b=>b.addEventListener("click",()=>signalToBug(b.dataset.signalbug)));document.querySelectorAll("[data-signaldismiss]").forEach(b=>b.addEventListener("click",()=>dismissSignal(b.dataset.signaldismiss)))}
function historyHtml(){''')

# Render friction view + counts.
sub(r'function render\(\)\{const titles=\{(.*?)history:\["Backlog & historik",`App v\$\{APP_VERSION\} · synkad backlog, versionshistorik och rollback`\]\};', r'''function render(){const titles={\1history:["Backlog & historik",`App v${APP_VERSION} · backlog, development jobs, versionshistorik och rollback`],friction:["Friktion","Lokal bevakning som letar efter återkommande UX-problem"]};''')
rep('document.getElementById("cBacklog").textContent=state.backlog.filter(b=>b.status!=="done").length;', 'document.getElementById("cBacklog").textContent=state.backlog.filter(b=>b.status!=="done").length;document.getElementById("cFriction").textContent=frictionOpen().length;')
rep('document.getElementById("addRow").style.display=["log","history"].includes(state.view)?"none":"grid";document.getElementById("search").style.display=state.view==="history"?"none":"block";', 'document.getElementById("addRow").style.display=["log","history","friction"].includes(state.view)?"none":"grid";document.getElementById("search").style.display=["history","friction"].includes(state.view)?"none":"block";')
rep('if(state.view==="history"){c.innerHTML=historyHtml();bindHistory();return}', 'if(state.view==="history"){c.innerHTML=historyHtml();bindHistory();return}if(state.view==="friction"){c.innerHTML=frictionHtml();bindFriction();return}')

# Backlog binding for development jobs.
rep('function bindHistory(){document.getElementById("backlogAddBtn")?.addEventListener("click",addBacklog);', 'function bindHistory(){document.getElementById("backlogAddBtn")?.addEventListener("click",addBacklog);document.getElementById("createDevJobBtn")?.addEventListener("click",createDevJob);')
rep('document.getElementById("copyPromptBtn")?.addEventListener("click",copyPrompt);', 'document.getElementById("copyPromptBtn")?.addEventListener("click",copyPrompt);document.querySelectorAll("[data-jcopy]").forEach(b=>b.addEventListener("click",()=>copyDevJob(b.dataset.jcopy)));document.querySelectorAll("[data-jhandoff]").forEach(b=>b.addEventListener("click",()=>handoffDevJob(b.dataset.jhandoff)));document.querySelectorAll("[data-jstatus]").forEach(x=>x.addEventListener("change",()=>setDevJobStatus(x.dataset.jstatus,x.value)));')

# Explicit action telemetry (works for keyboard too).
rep('function toggleComplete(t){pushUndo(t.completed?"reopen todo":"complete todo");', 'function toggleComplete(t){recordFrictionEvent("toggle",`complete:${t.id}`,{});pushUndo(t.completed?"reopen todo":"complete todo");')
rep('function toggleTag(t,tag){pushUndo(`toggle ${tag}`);', 'function toggleTag(t,tag){recordFrictionEvent("toggle",`${tag}:${t.id}`,{});pushUndo(`toggle ${tag}`);')
rep('function saveInline(){const t=findTask(state.inlineEditId);if(!t)return;', 'function saveInline(){const t=findTask(state.inlineEditId);if(!t)return;recordFrictionEvent("edit",`task:${t.id}`,{mode:"inline"});')
rep('function closeDrawer(saveChanges=true){const t=findTask(state.editingId);', 'function closeDrawer(saveChanges=true){const t=findTask(state.editingId);if(t&&saveChanges)recordFrictionEvent("edit",`task:${t.id}`,{mode:"drawer"});')
rep('function handleSyncError(e){console.error(e);', 'function handleSyncError(e){console.error(e);recordFrictionEvent("sync_error","dropbox",{kind:e.kind||"other"});')

# Generic no-op click monitor + nav/search events.
sub(r'function bind\(\)\{document\.querySelectorAll\("#nav button"\)\.forEach\(b=>b\.addEventListener\("click",\(\)=>\{state\.view=b\.dataset\.view;state\.inlineEditId=null;state\.selectedId=null;render\(\)\}\)\);document\.getElementById\("search"\)\.addEventListener\("input",e=>\{state\.query=e\.target\.value;render\(\)\}\);', '''function bind(){document.querySelectorAll("#nav button").forEach(b=>b.addEventListener("click",()=>{recordFrictionEvent("nav",b.dataset.view,{});state.view=b.dataset.view;state.inlineEditId=null;state.selectedId=null;render()}));document.getElementById("search").addEventListener("input",e=>{state.query=e.target.value;render();if(state.query.trim().length>=2)recordFrictionEvent("search","q:"+tinyHash(state.query.trim().toLowerCase()),{results:filtered().length,length:state.query.trim().length})});''')
# Append generic capture just before keydown binding at end of bind().
rep('document.getElementById("closeShortcuts").addEventListener("click",()=>document.getElementById("shortcutsModal").classList.remove("open"));document.addEventListener("keydown",handleKeyboard)}', '''document.getElementById("closeShortcuts").addEventListener("click",()=>document.getElementById("shortcutsModal").classList.remove("open"));document.addEventListener("click",e=>{if(TEST_MODE||!friction.enabled||e.target.closest("[data-friction-ui]"))return;const el=e.target.closest("button,[data-action],[data-collapse],.path-chip,.task-title");if(!el)return;const task=el.closest(".task"),key=el.dataset.action?`action:${el.dataset.action}:${task?.dataset.id||""}`:el.dataset.view?`view:${el.dataset.view}`:el.id?`id:${el.id}`:el.dataset.collapse?`collapse:${tinyHash(el.dataset.collapse)}`:`el:${el.className}`;const before=interactionFingerprint();setTimeout(()=>recordFrictionEvent("click",key,{changed:before!==interactionFingerprint()}),120)},true);document.addEventListener("keydown",handleKeyboard)}''')

# Synced schema: dev jobs; local friction deliberately excluded.
rep('function exportPayload(){return{app:"Doctrin Todo",version:DATA_VERSION,appVersion:APP_VERSION,exportedAt:new Date().toISOString(),updatedAt:state.updatedAt,tasks:state.tasks,backlog:state.backlog}}', 'function exportPayload(){return{app:"Doctrin Todo",version:DATA_VERSION,appVersion:APP_VERSION,exportedAt:new Date().toISOString(),updatedAt:state.updatedAt,tasks:state.tasks,backlog:state.backlog,devJobs:state.devJobs}}')
rep('function remotePayload(){return{app:"Doctrin Todo",version:DATA_VERSION,appVersion:APP_VERSION,updatedAt:state.updatedAt||new Date().toISOString(),tasks:state.tasks,backlog:state.backlog}}', 'function remotePayload(){return{app:"Doctrin Todo",version:DATA_VERSION,appVersion:APP_VERSION,updatedAt:state.updatedAt||new Date().toISOString(),tasks:state.tasks,backlog:state.backlog,devJobs:state.devJobs}}')
sub(r'function applyRemote\(data,rev\)\{.*?return !Array\.isArray\(data\.backlog\)\}', '''function applyRemote(data,rev){if(!data||!Array.isArray(data.tasks))throw new Error("Dropbox-filen har fel format");const remoteBacklog=Array.isArray(data.backlog)?data.backlog.map(normalizeBacklogItem):null,remoteJobs=Array.isArray(data.devJobs)?data.devJobs.map(normalizeDevJob):null;if((state.tasks.length||state.backlog.length||state.devJobs.length)&&hashData(state.tasks,state.backlog,state.devJobs)!==hashData(data.tasks.map(normalizeTask),remoteBacklog||state.backlog,remoteJobs||state.devJobs))createSnapshot("Before Dropbox pull");state.tasks=data.tasks.map(normalizeTask);if(remoteBacklog)state.backlog=remoteBacklog;else if(!state.backlog.length)state.backlog=seedBacklog();if(remoteJobs)state.devJobs=remoteJobs;state.updatedAt=data.updatedAt||new Date().toISOString();syncState.remoteRev=rev;storeRemoteRev();saveLocal(false);render();return !Array.isArray(data.backlog)||!Array.isArray(data.devJobs)}''')
rep('const remoteTasks=(remote.data.tasks||[]).map(normalizeTask),remoteBacklog=Array.isArray(remote.data.backlog)?remote.data.backlog.map(normalizeBacklogItem):state.backlog,localHash=hashData(),remoteHash=hashData(remoteTasks,remoteBacklog),', 'const remoteTasks=(remote.data.tasks||[]).map(normalizeTask),remoteBacklog=Array.isArray(remote.data.backlog)?remote.data.backlog.map(normalizeBacklogItem):state.backlog,remoteJobs=Array.isArray(remote.data.devJobs)?remote.data.devJobs.map(normalizeDevJob):state.devJobs,localHash=hashData(),remoteHash=hashData(remoteTasks,remoteBacklog,remoteJobs),')
rep('setSyncStatus("syncing","Sparar…","Skriver todos + backlog till Dropbox/todos.json.");', 'setSyncStatus("syncing","Sparar…","Skriver todos + backlog + development jobs till Dropbox/todos.json.");')

# History snapshot copy.
rep('${(s.tasks||[]).length} todos · ${(s.backlog||[]).length} backlog · app v${esc(s.version||"?")}', '${(s.tasks||[]).length} todos · ${(s.backlog||[]).length} backlog · ${(s.devJobs||[]).length} dev jobs · app v${esc(s.version||"?")}')

# Tests: restore local friction key, initialize models, append v4.2 coverage before summary.
rep('const original={[STORAGE_KEY]:localStorage.getItem(STORAGE_KEY),[SNAPSHOT_KEY]:localStorage.getItem(SNAPSHOT_KEY),[WEEK_KEY]:localStorage.getItem(WEEK_KEY),[COLLAPSE_KEY]:localStorage.getItem(COLLAPSE_KEY)};', 'const original={[STORAGE_KEY]:localStorage.getItem(STORAGE_KEY),[SNAPSHOT_KEY]:localStorage.getItem(SNAPSHOT_KEY),[WEEK_KEY]:localStorage.getItem(WEEK_KEY),[COLLAPSE_KEY]:localStorage.getItem(COLLAPSE_KEY),[FRICTION_KEY]:localStorage.getItem(FRICTION_KEY)};')
rep('state.tasks=[];state.backlog=seedBacklog();state.updatedAt=new Date().toISOString();state.query="";state.view="open";', 'state.tasks=[];state.backlog=seedBacklog();state.devJobs=[];friction=defaultFriction();state.updatedAt=new Date().toISOString();state.query="";state.view="open";')
anchor='await test("Collapsed paths persist locally",()=>{state.collapsed=new Set(["x"]);saveCollapsed();state.collapsed=new Set();loadCollapsed();assert(state.collapsed.has("x"))});'
extra='''
await test("Data version is 6",()=>assert(DATA_VERSION===6));
await test("Development job normalizes",()=>{const j=normalizeDevJob({prompt:"x",backlogIds:["b"]});assert(j.status==="ready"&&j.backlogIds[0]==="b")});
await test("Development job prompt uses selected backlog",()=>{state.backlog=[normalizeBacklogItem({id:"b1",type:"bug",title:"Fix",selected:true,comment:"careful"})];state.devJobs=[];const j=createDevJob();assert(j&&j.prompt.includes("[BUG] Fix")&&j.prompt.includes("careful"))});
await test("Development job stored in export",()=>assert(exportPayload().devJobs.length===1));
await test("Development job stored in remote payload",()=>assert(remotePayload().devJobs.length===1));
await test("Legacy v5 without devJobs preserves empty jobs",()=>{state.devJobs=[];importData(JSON.stringify({version:5,tasks:[{title:"legacy"}],backlog:[{title:"b"}]}));assert(state.devJobs.length===0)});
await test("Friction telemetry defaults enabled",()=>{friction=defaultFriction();assert(friction.enabled&&friction.events.length===0)});
await test("Repeated no-op clicks create signal",()=>{friction=defaultFriction();for(let i=0;i<3;i++)recordFrictionEventForTest("click","action:test",{changed:false});assert(friction.signals.some(x=>x.kind==="repeated-noop"))});
await test("Undo burst creates signal",()=>{friction=defaultFriction();for(let i=0;i<3;i++)recordFrictionEventForTest("undo","global",{});assert(friction.signals.some(x=>x.kind==="undo-burst"))});
await test("Toggle loop creates signal",()=>{friction=defaultFriction();for(let i=0;i<4;i++)recordFrictionEventForTest("toggle","next:t1",{});assert(friction.signals.some(x=>x.kind==="toggle-loop"))});
await test("Edit churn creates signal",()=>{friction=defaultFriction();for(let i=0;i<4;i++)recordFrictionEventForTest("edit","task:t1",{});assert(friction.signals.some(x=>x.kind==="edit-churn"))});
await test("Navigation bounce creates signal",()=>{friction=defaultFriction();["today","next","today","next","today","next"].forEach(v=>recordFrictionEventForTest("nav",v,{}));assert(friction.signals.some(x=>x.kind==="nav-bounce"))});
await test("Repeated failed search creates signal without query text",()=>{friction=defaultFriction();for(let i=0;i<3;i++)recordFrictionEventForTest("search","q:abc",{results:0,length:6});assert(friction.signals.some(x=>x.kind==="search-miss"));assert(!JSON.stringify(friction).includes("secretquery"))});
await test("Friction signal converts to synced bug",()=>{state.backlog=[];friction=defaultFriction();const x=emitFrictionSignal("test","control","Testproblem","Tre klick utan effekt.",4);signalToBug(x.id);assert(state.backlog.length===1&&state.backlog[0].type==="bug"&&x.status==="backlog")});
await test("Friction dismissal works",()=>{friction=defaultFriction();const x=emitFrictionSignal("test2","control","Ignore","desc",2);dismissSignal(x.id);assert(x.status==="dismissed"&&friction.dismissed===1)});
await test("Friction event data is local-only",()=>{friction=defaultFriction();recordFrictionEventForTest("undo","global",{});assert(!Object.prototype.hasOwnProperty.call(remotePayload(),"friction"))});
await test("Friction signal cooldown deduplicates",()=>{friction=defaultFriction();emitFrictionSignal("same","x","A","B",2);emitFrictionSignal("same","x","A","B",2);assert(friction.signals.length===1)});
await test("Friction dashboard renders privacy note",()=>{friction=defaultFriction();assert(frictionHtml().includes("lagras endast lokalt"))});
await test("Current version is 4.2.0",()=>assert(VERSION_HISTORY[0].version==="4.2.0"));
'''
rep(anchor,anchor+extra)
# Existing version test must now expect 4.2.
rep('await test("Version history includes 4.1.0",()=>assert(VERSION_HISTORY[0].version==="4.1.0"));', 'await test("Version history retains 4.1.0",()=>assert(VERSION_HISTORY.some(x=>x.version==="4.1.0")));')

p.write_text(s,encoding='utf-8')
print('patched',len(s),'bytes')
